
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

#env:
  #AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  #AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  #NODE_VERSION: '20.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.18.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install and Build in Server Folder
      run: |
        cd server
        npm install rimraf@latest glob@latest formidable@latest
        npm audit fix --force
        rm -rf node_modules
        npm install
        npm run build

    # - name: Run the tests
    #   # run: npm test

    # - name: Build
    #   run: npm run build