name: CI/CD Pipeline for Node.js API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: |
        cd server
        npm install express
        npm install --save-dev jest supertest eslint
        npm init -y
        npm install

    - name: Build Application
      run: |
        cd server
        npm install --save-dev webpack webpack-cli
        npm run build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "machine api.heroku.com
          login ${{ secrets.HEROKU_EMAIL }}
          password ${{ secrets.HEROKU_API_KEY }}" > ~/.netrc
  
      - name: Deploy to Heroku
        run: git push https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git HEAD:main

